- name: "Copy nginx.conf"
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: "0644"
    owner: root
    group: root
  notify: reload nginx

- name: "Copy nginx configs"
  copy:
    src: files/conf.d/
    dest: /etc/nginx/conf.d/
    mode: "0644"
    owner: root
    group: root
  notify: reload nginx

- name: "Create ssl configuration files"
  template:
    src: ssl_host.conf.j2
    dest: /etc/nginx/conf.d/{{ item }}.conf
    mode: "0644"
    owner: root
    group: root
  with_items: "{{ domain_list }}"
  notify: reload nginx
