- name: "Install nginx"
  apt:
    name:
      - nginx
    state: present
    update_cache: true

- name: "Enable and start nginx service"
  systemd:
    name: nginx
    state: started
    enabled: true
    daemon_reload: true
