- name: "Create group"
  group:
    name: "{{ MINECRAFT_GROUP }}"
    state: present
    system: true

- name: "Create user"
  user:
    name: "{{ MINECRAFT_USER }}"
    group: "{{ MINECRAFT_GROUP }}"
    home: "{{ MINECRAFT_HOME }}"

- name: "Start installation"
  include_role:
    name: "{{ MINECRAFT_TYPE }}.yml"
