- name: "Create group"
  group:
    name: "{{ minecraft_group }}"
    state: present
    system: true

- name: "Create user"
  user:
    name: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    home: "{{ minecraft_home }}"
    shell: /bin/bash

- name: "Start installation"
  include_tasks: "{{ minecraft_type }}.yml"
