- name: "Install dependencies"
  apt:
    name: "{{ paper_pkgs }}"
    state: present
    update_cache: true

- name: "Create server folder"
  file:
    path: "{{ minecraft_home }}"
    state: directory
    mode: "0755"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"

- name: "Create server subfolders"
  file:
    path: "{{ minecraft_home }}/{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
  with_items:
    - logs
    - plugins

- name: "Download paper jar"
  get_url:
    url: "{{ paper_download_url }}"
    dest: "{{ minecraft_home }}/server.jar"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: "0755"

- name: "Agree to EULA"
  copy:
    src: eula.txt
    dest: "{{ minecraft_home }}/eula.txt"
    mode: "0644"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"

- name: "Copy scripts"
  copy:
    src: files/scripts/
    dest: "{{ minecraft_home }}"
    mode: "0755"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
