- name: "Install dependencies"
  apt:
    name: "{{ SPIGOT_PKGS }}"
    state: present
    update_cache: yes

- name: "Create server folder"
  file:
    path: "{{ MINECRAFT_HOME }}"
    state: directory
    mode: 0755
    owner: "{{ MINECRAFT_USER }}"
    group: "{{ MINECRAFT_GROUP }}"

- name: "Create server subfolders"
  file:
    path: "{{ MINECRAFT_HOME }}/{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ MINECRAFT_USER }}"
    group: "{{ MINECRAFT_GROUP }}"
  with_items:
    - logs
    - plugins

- name: "Create temporary folder for BuildTools"
  file:
    path: /tmp/buildtools
    state: directory
    mode: 0755

- name: "Download BuildTools"
  get_url:
    url: "{{ SPIGOT_DOWNLOAD_URL }}"
    dest: /tmp/buildtools/

- name: "Build spigot.jar file"
  command: 'java -jar /tmp/buildtools/BuildTools.jar --rev {{ MINECRAFT_VERSION }}'
  args:
    creates: 'spigot-{{ MINECRAFT_VERSION }}.jar'
    chdir: '/tmp/buildtools'
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/graalvm-ce-java{{ JAVA_VERSION }}-{{ GRAALVM_VERSION }}/bin
    JAVA_HOME: /opt/graalvm-ce-java{{ JAVA_VERSION }}-{{ GRAALVM_VERSION }}
    SHELL: /bin/bash

- name: "Copy spigot.jar to server folder"
  copy:
    src: /tmp/buildtools/spigot-{{ MINECRAFT_VERSION }}.jar
    dest: "{{ MINECRAFT_HOME }}/server.jar"
    remote_src: yes

- name: "Agree to EULA"
  copy:
    src: eula.txt
    dest: "{{ MINECRAFT_HOME }}/eula.txt"
    mode: 0644
    owner: "{{ MINECRAFT_USER }}"
    group: "{{ MINECRAFT_GROUP }}"

- name: "Copy scripts"
  copy:
    src: files/scripts/
    dest: "{{ MINECRAFT_HOME }}"
    mode: 0755
    owner: "{{ MINECRAFT_USER }}"
    group: "{{ MINECRAFT_GROUP }}"

- name: "Remove tmp files from the server"
  file:
    path: /tmp/buildtools/
    state: absent
