- name: "Install dependencies"
  apt:
    name: "{{ spigot_pkgs }}"
    state: present
    update_cache: true

- name: "Create server folder"
  file:
    path: "{{ minecraft_home }}"
    state: directory
    mode: "0755"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"

- name: "Create server subfolders"
  file:
    path: "{{ minecraft_home }}/{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
  with_items:
    - logs
    - plugins

- name: "Create temporary folder for BuildTools"
  file:
    path: /tmp/buildtools
    state: directory
    mode: "0755"

- name: "Download BuildTools"
  get_url:
    url: "{{ spigot_download_url }}"
    dest: /tmp/buildtools/
    mode: "0755"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"

- name: "Build spigot.jar file"
  command: 'java -jar /tmp/buildtools/BuildTools.jar --rev {{ minecraft_version }}'
  args:
    creates: 'spigot-{{ minecraft_version }}.jar'
    chdir: '/tmp/buildtools'
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/graalvm-ce-java{{ java_version }}-{{ graalvm_version }}/bin
    JAVA_HOME: /opt/graalvm-ce-java{{ java_version }}-{{ graalvm_version }}
    SHELL: /bin/bash

- name: "Copy spigot.jar to server folder"
  copy:
    src: /tmp/buildtools/spigot-{{ minecraft_version }}.jar
    dest: "{{ minecraft_home }}/server.jar"
    remote_src: true
    mode: "0755"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"

- name: "Agree to EULA"
  copy:
    src: eula.txt
    dest: "{{ minecraft_home }}/eula.txt"
    mode: "0644"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"

- name: "Copy scripts"
  copy:
    src: files/scripts/
    dest: "{{ minecraft_home }}"
    mode: "0755"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"

- name: "Remove tmp files from the server"
  file:
    path: /tmp/buildtools/
    state: absent
