- name: "Installing cpufrequtils"
  apt:
    name: cpufrequtils
    update_cache: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: "Replace config parameters"
  lineinfile:
    path: /etc/init.d/cpufrequtils
    regexp: 'GOVERNOR=\"[a-zA-Z]+\"'
    line: 'GOVERNOR="perfomance"'
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  register: cpufreq_config

- name: "Add cpufreq to autorun"
  systemd:
    name: cpufrequtils
    enabled: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: "Reload cpufreq"
  systemd:
    state: restarted
    name: cpufrequtils
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and cpufreq_config.changed
