- name: "Install server config file"
  template:
    src: server.cnf.j2
    dest: "{{ MARIADB_CONFIG_SERVER }}"
  notify: restart mariadb

- name: "Install network config file"
  template:
    src: network.cnf.j2
    dest: "{{ MARIADB_CONFIG_NETWORK }}"
  notify: restart mariadb

- name: "Install custom config file"
  template:
    src: custom.cnf.j2
    dest: "{{ MARIADB_CONFIG_CUSTOM }}"
  notify: restart mariadb

- name: "Check if sysctl executable exists. If not, swappiness cannot be set!"
  stat:
    path: /usr/sbin/sysctl
  register: sysctl_check

- name: "Configure swappiness"
  sysctl:
    name: vm.swappiness
    value: "{{ mariadb_swappiness }}"
    state: present
  when:
    - mariadb_configure_swappiness|bool
    - sysctl_check.stat.exists

- name: "Create log directory"
  file:
    state: directory
    path: /var/log/mariadb
    owner: mysql
    group: mysql
    mode: 0755
  when: mariadb_logrotate.configure|bool

- name: "Configure logrotate"
  template:
    src: etc_logrotate.d_mysql.j2
    dest: /etc/logrotate.d/mysql
  when: mariadb_logrotate.configure|bool
  notify: restart mariadb

- name: "Ensure service is started"
  service:
    name: "{{ mariadb_service }}"
    state: started
    enabled: true
