- name: "Creqte Node Exporter group"
  group:
    name: {{ node_exporter_group }}
    system: yes
    state: present

- name: "Create Node Exporter user"
  user:
    name: {{ node_exporter_user }}
    group: {{ node_exporter_group }}
    create_home: no
    state: present
    shell: /sbin/nologin
    system: yes

- name: "Download Node Exporter archive"
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp/node_exporter/

- name: "Extract Node Exporter"
  unarchive:
    src: /tmp/node_exporter/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
    dest: /tmp/node_exporter/

- name: "Copy Node Exporter binary"
  copy:
    src: /tmp/node_exporter/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter
    dest: /usr/local/bin/
    owner: {{ node_exporter_user }}
    group: {{ node_exporter_group }}
    mode: 0644

- name: "Clear temporary files"
  file:
    src: /tmp/node_exporter
    state: absent

- name: "Create Node Exporter service"
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644

- name: "Start Node Exporter service"
  systemd:
    name: node_exporter.service
    daemon_reload: yes
    enabled: yes
    state: started
