- name: "Add required modules"
  modprobe:
    name: "{{ item }}"
    state: present
  with_items: "{{ modprobe_modules }}"

- name: "Configure sysctl"
  template:
    src: sysctl.conf.j2
    dest: /etc/sysctl.conf
  notify: reload sysctl
